### ISSUE TITLE
hey man, cli cmd doesnt seems to be working after the first util method being installed. Could take a look ? i mean should raise this issue with step to reproduce seems like a bug.

### ISSUE THREAD

**Issue by jrTilak** [jrTilak/lazykit#73]
> hey man, cli cmd doesnt seems to be working after the first util method being installed. Could take a look ? i mean should raise this issue with step to reproduce seems like a bug.

_Originally posted by @ebe25 in https://github.com/jrTilak/lazykit/issues/63#issuecomment-2101086133_

**Comment by jrTilak** [comment]
@ebe25 Can you provide the steps to reproduction or more details?

**Comment by ebe25** [comment]
@jrTilak  nope mb, you can close this issue, seems like the cli add methods are working.
