### ISSUE TITLE
BUG: Shows version twice after project init

### ISSUE THREAD

**Issue by jrTilak** [jrTilak/lazykit#79]
**Describe the bug**
![image](https://github.com/jrTilak/lazykit/assets/106688422/a2b2d891-27cb-49b6-a103-4e924b2afb78)

**To Reproduce**
Init a project using `npx @jrtilak/lazykit@latest init`

**Expected behavior**
Show show version number only once.

**Comment by mxthxngx** [comment]
Hey @jrTilak could I take this up? 
If yes, could you give me some information about how I can run it locally to see if the issue is fixed (First time Open source contributor :P )

**Comment by jrTilak** [comment]
Yes absolutely!

I suppose you might know the basic setup step. For cli specifically after installing dependencies
1. To watch the changes for cli and start development server.
```bash
pnpm run watch:cli
```
2. To install the package locally for testing
```bash
cd src/cli
```
```bash
npm i -g
```

And now you can use the lazykit cli using `lazykit` as command name which will be  executing from you local codebase. Any changes in your codebase will be reflected
- Example
```bash
lazykit init
```

### And for the issue
- See `src/cli/src/scripts/init.ts` and you will easily find what's the issue.

_let me know if you face any isssues_

**Comment by jrTilak** [comment]
as per #80
